### ISSUE TITLE
multiple WSIs for one patient

### ISSUE THREAD

**Issue by zli1893** [taliq/TEA-graph#2]
Congratulation!

How does the Tea-graph process multiple WSIs for one patient when training and tesing? 
For example, all WSIs are treated as independent cases when training whether or not they belong to the same patient？same as testing?

**Comment by taliq** [comment]
Thanks for your interest in our paper, and sorry for the late reply.
We randomly pick a single WSI if there are multiple WSIs for one patient.
However, you can consider post-process the predicted risk value for multiple WSIs for better results.
Thanks
