### ISSUE TITLE
Paper question

### ISSUE THREAD

**Issue by han-yeol** [taliq/TEA-graph#3]
Hi

I have a further question about your paper.
In your paper, method, Survival prediction using GAT chapter
You said that pi_i is the list of patients who have shorter survival times than patient i

From what I understand, To minimize loss, pi_i should be a longer patients not the shorter (High risk, short survival times)  
please let me know what I miss

**Comment by taliq** [comment]
Thanks for your interest in our paper.
I checked the original paper again, and there is a typo. 
As you mentioned, pi_i is the patients who survive longer than the target one.
You can check the code that we implemented it in the right way :)

Sorry for confusing you, and thanks for the correction.

If you need any further questions, contact me anytime through GitHub or email

Thanks

**Comment by Luxiaowen45** [comment]
I am a beginner. I would like to ask, the article says that distance {d} and Angle {a} are embedded as edge features. Take the length,d ={d11,d12,... dNN}, where d11 and patch feature dimensions are consistent, what is the specific calculation method for distance d? Are the corresponding elements of two node eigenvectors subtracted?
